trigger:
- master

resources:
  repositories:
    - repository: templates
      type: GitHub
      name: divvun/divvun-ci-config
      endpoint: divvun-ci

jobs:
  - template: repo/templates/keyboards.yml@templates
    parameters:
      name: sms
      packageName: keyboard-sms
      kbdgenFolder: "sms.kbdgen"
      repositoryWin: "https://pahkat.uit.no/repo/windows"
      repositoryMac: "https://pahkat.uit.no/repo/macos"
      languages:
        - projectjjName: giella-sms
          path: usr/share/giella/mobilespellers/sms-mobile.zhfst
          name: sms
