internalName: sms

locales:
  en:
    name: &bundleName "Skolt Sami Keyboards"
    description: "Keyboards for the Skolt Sami language from UiT."
  nb:
    name: "Skoltesamisk tastatur"
    description: "Tastatur for skoltesamisk fra UiT."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts:
  - sms-mobile
  - sms-macos
  - sms-win

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.sms
    icon: images/sms-icon.png
    keyStore: $GTPRIV/admin/dev-accounts/dev_keys/sami_keyboard.keystore
    keyAlias: sami_keyboard

  ios: &AppleID
    codeSignId: "Developer ID Installer: The University of Tromso (2K5J2584NX)"
    provisioningProfileId: Test
    packageId: no.uit.giella
    bundleName: *bundleName
    icon: images/sms-icon.png

  osx:
    <<: *AppleID
    icon: images/sms-keyboard-menu-icon.png
    version: 0.2.1
    resources: doc

  win:
    appName: *bundleName
    version: 0.1.4
    url: "http://divvun.no"
    uuid: "5D5F44C7-9716-4B33-BB99-EB3717ECDCFB"
