locales:
  en:
    name: Skolt Sami Keyboards
    description: Keyboards for the Skolt Sami language.
  fi:
    name: Koltansaamen näppäimistöt
    description: Näppäimistöt koltansaamen kielelle.
  sms:
    name: Nuõrttsääʹmǩiõll puällpååʹrd
    description: Puällpååʹrd nuõrttsääʹmǩiõʹlle.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
