name: CI

on:
  pull_request:
  push:
    branches:
    - master
    - develop

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: run kbdgen
      run: |
        # from divvun/actions/setup
        $Env:CODESIGN_PFX = "$pwd\enc\creds\windows\divvun.pfx"

        # fetch msklc
        curl -o 6aa798a39c.zip https://x.brendan.so/6aa798a39c.zip
        7z x 6aa798a39c.zip
        $Env:MSKLC_PATH = "$pwd\msklc1.4"

        Write-Output "everything is actually okay"

        ./kbdgen.exe build win -R --ci -o output .

        Write-Output "thanks"
    - name: Upload windows klc
      uses: actions/upload-artifact@v2
      with:
        name: windows-klc
        path: 'output'

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Divvun CI
      uses: divvun/actions/setup@5e407bf8f794dfe805d78afcb348a5cb871d1e26
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: run kbdgen
      run: |
        set -e

        brew install imagemagick yq

        export TARGET_BUNDLE_NAME=$(yq r sms.kbdgen/targets/mac.yaml bundleName)
        export TARGET_VERSION=$(yq r sms.kbdgen/targets/mac.yaml version)

        spctl -a -vvv -t exec kbdgen
        kbdgen build mac -R --ci -o output .
    - name: Upload mac pkg
      uses: actions/upload-artifact@v2
      with:
        name: mac-pkg
        path: 'output'
